name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run lint:format
      - run: npm run lint
      - run: npm run lint:circular
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20', '22.4.x']
    name: Testing on node ${{ matrix.node }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - uses: ./.github/actions/install
        with:
          node: ${{ matrix.node }}
      - run: npm run test
